### ISSUE TITLE
Bot not visiting Colombian Senate scrapers

### ISSUE THREAD

**Issue by wfdd** [everypolitician/everypolitician-data#14961] opened 2016-08-03 12:13 UTC
The bot's not listed among the users who've downloaded the data on Morph.io and there should've been some Wikidata updates by now.

**Comment by davewhiteland** [comment] 2016-08-04 16:27
@wfdd ooh, thanks for pointing this out. I've added a webhook to trigger it.

The way we're doing it with pretty much all of ours now is to have just one of the morph scrapers for any given legislature notify the bot when it has run, by adding a webhook that triggers the bot to run rebuilder.

Of course we  _could_ do that on each and every one of the scrapers, but in practice we're happy to have only one webhook from just one of the sources (because when the rebuilder runs, it fetches the data from all the other sources anyway, i.e., the other scrapers too) and we're happy to run this on a once-per-day basis[1]. Simply as a policy of convenience, we've generally ended up putting the webhooks on the wikidata scrapers simply because there's one of those for every legislature now, and they're all running on morph (which makes it easy to add a webhook to hit on completion and of course that's also nicely on a once-every-24-hours frequency).

In this case I've just added it to our Colombian Senator twitter scraper, so we should see things tumble through sometime in the next 24 hours...

[1] after all, there is a human moderator in the chain too

**Comment by wfdd** [comment] 2016-08-04 16:50
Thanks @davewhiteland.  I assume this change happened sometime in the last month?  I could transfer ownership of the Wikidata scraper, if that makes things easier.

Cabo Verde not receiving updates either.

**Comment by davewhiteland** [comment] 2016-08-04 17:09
@wfdd, no I don't think it has ever been in place for the Colombian Senate; but the data got through because the build has been run manually (hence I'm shown as a downloader, not the bot/ep account). (I am a little concerned that the Senators' twitter scraper was set to autorun on morph.io, but has not been autorunning, but that's a separate problem.) I'm raising an issue now on how we can better notice this sort of thing: @tmtmtmtm has set up an autopopulated spreadsheet that shows lots of useful things including days since last modification (and yes the cells do go red!) but it's not always obvious that it's a pathological problem, and we (well, certainly not me) might not be actively looking for such failures (yet).

**Comment by wfdd** [comment] 2016-08-04 17:24
> no I don't think it has ever been in place for the Colombian Senate ...

I falsely assumed webhooks weren't being used before, but I see there'd been another scraper in all other legislatures I've contributed to.  Sorry for the confusion/diversion.

**Comment by davewhiteland** [comment] 2016-08-04 23:22
> Sorry for the confusion/diversion

@wfdd on the contrary, I think this is an excellent example of how superhelpful it is to have contributors outside our team! 👍 

I'll close this issue when I've confirmed we've had a data PR go right through to the site; I notice the first stage is satisfied, and the bot _has_ downloaded data from [your Colombian wikidata scraper](https://morph.io/wfdd/colombia-senado-wikidata-scraper), and the (webhooked) [Twitter handle one](https://morph.io/everypolitician-scrapers/twitter-colombia-senate-list) too.

**Comment by davewhiteland** [comment] 2016-08-12 10:36
Looks like the bot and its attendant humans are handling this routinely now, so closing :-)

(eg, [data PR 15426](https://github.com/everypolitician/everypolitician-data/pull/15426) and [data PR 15439](https://github.com/everypolitician/everypolitician-data/pull/15439)).

**Closed by davewhiteland** 2016-08-12 10:36 UTC
