### ISSUE TITLE
Broken Import: Poland/Sejm

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#16404] opened 2016-09-02 10:40 UTC
## Legislature

Poland/Sejm
## Problem

Lots of Wikidata going missing

**Comment by octopusinvitro** [comment] 2016-09-08 17:08
Looks like the problem is back in #16675, although it was marked as solved in the [TODO](https://github.com/everypolitician/everypolitician/issues/496) list.

Unckecking the TODO checkbox until the problem is solved.

**Comment by octopusinvitro** [comment] 2016-09-08 17:09
Looks like the problem is back in #16675, although it was marked as solved in the [TODO](https://github.com/everypolitician/everypolitician/issues/496) list.

Unckecking the TODO checkbox until the problem is solved.

**Closed** 2017-02-06 10:29 UTC
Labels: broken import
